travis:
  secure:
    BINSTAR_TOKEN: Nm3PZ887h4pG7mqqBy0MobKGSBPhHSRPKHFGx0hS2jo1h9EPKmVX5CP6uLDZd6XpWPApYBYV80FiV5i3oAiSfXBoIx26n1B0xQpENGGqIekc1Ns6+/PandFzU3OVrlm0niUcOiPNK0YUz9Q9/aujYnQ+o/AqzsgboD0agMWkLhSchXGBjDLrydLEoh9N2s8GLwh/WbZTvfqoHTatjfwyyfmMs1hgryfO92Z1BJo2jG0yzU79gH9T0iPpvWAhUm49+UwuOGf+LqkHHoeVy1QGVU0zDnfewQFgjrdGseOZjOYDWxTet3pOZaSUeKQ/wmSkNzKV6/yJPLwE6PXkGBb2YarUkQtEvsMVKaY3gY0EL9tWKJnvgrvRc9uwt7zbw8oNvXCyMMBq3i2qvzZ/dXSWj/069g0GCxr9Jm9DSBbp4pgFvO2WuN59MHeSSX9aaIQNUBrM1rZIVZ48VvMQZI5W+naN8q6Qsfz+yWKZIM6OEZwIh3IyLnR9JMimQGkw6+LZ2ue9jH2MiuaDXz0zkXYT213fxRU5xzpDb7Rseex7YDab3Zj6b6o9IlY9fjt2TRaiALlr1l98SqYAQfgLvx68RSTddZbTHd+LCCly3FJfT5nKip9H8KXev2/KVDZ5EjSmjAPvOZdi5xTJTfUKbBfrRiP8RNo7Q3zND6BfKVZyp7o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
